#!/bin/sh

[ -f $XINITRC ] && alias startx="startx $XINITRC"

alias ls="ls -hN --group-directories-first"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias dotfiles="git --git-dir=$HOME/dotfiles --work-tree=$HOME"

alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

mkcd()
{
	mkdir -p -- "$1" &&
	cd    -P -- "$1"
}

