#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"

export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="st"
export BROWSER="firefox"

export ASAN_OPTIONS=abort_on_error=1:print_legend=0

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

source $XDG_CONFIG_HOME/user-dirs.dirs

export XINITRC=$XDG_CONFIG_HOME/x11/xinitrc
export HISTFILE=$XDG_STATE_HOME/bash/history
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
export WINEPREFIX=$XDG_DATA_HOME/wineprefixes/default
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive
export ELECTRUMDIR=$XDG_DATA_HOME/electrum
export GRANDLE_USER_HOME=$XDG_DATA_HOME/grandle

export C_INCLUDE_PATH=$HOME/.local/include
export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
export LIBRARY_PATH=$HOME/.local/lib
export PKG_CONFIG_PATH=$LIBRARY_PATH/pkgconfig
export MANPATH=$XDG_DATA_HOME/man:$TEXLIVE/texmf-dist/doc/man:$(manpath)
export INFOPATH=$TEXLIVE/texmf-dist/doc/info
export PROTON_USE_WINED3D=1

export MAKEFLAGS="-j$(nproc)"

# programing languages path
export CARGO_HOME=$XDG_DATA_HOME/cargo
export GOPATH=$XDG_DATA_HOME/go

export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python
export PYTHON_HISTORY=$XDG_STATE_HOME/python/hystory

# exec startx

